name: CI

on:
  push:
    branches:
      - main
      - master

  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "latest"

      - name: Install dependencies
        run: bun ci

      - name: Check Gleam
        run: bun run check

      - name: Build Gleam
        run: bun run gleam

      - name: Typecheck TypeScript
        run: bun run typecheck

      - name: Build site
        run: bun run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: personal-site
          path: dist/
